{% set name = "eth-utils" %}
{% set version = "5.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1f096867ac6be895f456fa3acb26e9573ae66e753abad9208f316d24d6178156

build:
  number: 0
  skip: true  # [py<3.8]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
    - cytoolz >=0.10.1  # [python_impl == 'cpython']
  run:
    - eth-hash >=0.3.1
    - eth-typing >=5.0.0
    - toolz >0.8.2  # [python_impl == 'pypy']
    - cytoolz >=0.10.1  # [python_impl == 'cpython']
    - python

test:
  imports:
    - eth_utils
    - eth_utils.curried
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth_utils
  summary: Common utility functions for ethereum codebases.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
