{% set name = "eth-utils" %}
{% set version = "5.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a5eb9555f43f4579eb83cb84f9dda9f3d6663bbd4a5a6b693f8d35045f305a1f

build:
  number: 0
  skip: true  # [py<3.8]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
    - cytoolz <1.0.0,>=0.10.1  # [python_impl == 'cpython']
  run:
    - cached-property <2,>=1.5.2  # [py<3.8]
    - eth-hash >=0.3.1
    - eth-typing >=5.0.0
    - hexbytes >=1.0.0
    - toolz >0.8.2  # [python_impl == 'pypy']
    - cytoolz >=0.10.1  # [python_impl == 'cpython']
    - python

test:
  imports:
    - eth_utils
    - eth_utils.curried
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth_utils
  summary: Common utility functions for ethereum codebases.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
