{% set name = "eth-utils" %}
{% set version = "1.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf82762a46978714190b0370265a7148c954d3f0adaa31c6f085ea375e4c61af

build:
  number: 0
  skip: true  # [py>=40 or py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - cytoolz <1.0.0,>=0.10.1  # [python_impl == 'cpython']
  run:
    - cytoolz <1.0.0,>=0.10.1  # [python_impl == 'cpython']
    - eth-hash <1.0.0,>=0.1.0
    - eth-typing <3.0.0,>=2.2.1
    - python
    - toolz <1,>0.8.2  # [python_impl == 'pypy'] 

test:
  imports:
    - eth_utils
    - eth_utils.curried
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth_utils
  summary: Common utility functions for ethereum codebases.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
