{% set name = "eth-utils" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fcb4c3c1b32947ba92970963f9aaf40da73b04ea1034964ff8c0e70595127138

build:
  number: 0
  skip: true  # [py>=40 or py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - cytoolz <1.0.0,>=0.10.1  # [python_impl == 'cpython']
  run:
    - cytoolz <1.0.0,>=0.10.1  # [python_impl == 'cpython']
    - eth-hash <0.6.0,>=0.3.1
    - eth-typing <4.0.0,>=3.0.0
    - python
    - toolz <1,>0.8.2  # [python_impl == 'pypy']
    - cached-property <2,>=1.5.2  # [py<3.8]

test:
  imports:
    - eth_utils
    - eth_utils.curried
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth_utils
  summary: Common utility functions for ethereum codebases.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
