{% set name = "eth-utils" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32f50edb14c5be0c4f0e8c2e6117286ccc5dfda21d170f358add554a048398e3

build:
  number: 2
  skip: true  # [py>=40 or py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - cytoolz <1.0.0,>=0.10.1  # [python_impl == 'cpython']
  run:
    - cytoolz <1.0.0,>=0.10.1  # [python_impl == 'cpython']
    - eth-hash <4.0.0,>=0.3.1
    - eth-typing <4.0.0,>=3.0.0
    - python
    - toolz <1,>0.8.2  # [python_impl == 'pypy'] 

test:
  imports:
    - eth_utils
    - eth_utils.curried
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth_utils
  summary: Common utility functions for ethereum codebases.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
